env:
  browser: true
  commonjs: true
  es6: true
  screeps/screeps: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Cache: writable
  Log: writable
  T: writable
  describe: readonly
  it: readonly
  MemoryCache: writable
parserOptions:
  ecmaVersion: 2018
rules:
  prefer-const: error
  semi: [error, never]
  quotes: error
  indent: error
  no-shadow: error
plugins:
  - 'screeps'

