env:
  browser: true
  commonjs: true
  es6: true
  screeps/screeps: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  prefer-const: error
  semi: [error, never]
plugins:
  - 'screeps'

