{
 "title": "City Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "city", "label": "City", "query": "screeps.yoner.cities.*" }
  ]
 },
 "panels": [
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "city",
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  },
  {
   "title": "$city",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.rcl.level"
      }
     ]
    },
    {
     "title": "RCL Upgrade Progress",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.rcl.progress, screeps.yoner.cities.$city.rcl.progressTotal)"
      }
     ]
    },
    {
     "title": "RCL Upgrade Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "scale(divideSeries(#B, #A), 3)",
       "targetFull": "scale(divideSeries(movingAverage(diffSeries(screeps.yoner.cities.$city.rcl.progressTotal, screeps.yoner.cities.$city.rcl.progress), '5min'), perSecond(movingAverage(screeps.yoner.cities.$city.rcl.progress, '1hour'))), 3)"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "screeps.yoner.cities.$city.storage.energy"
      }
     ]
    },
    {
     "title": "Spawn Energy",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(screeps.yoner.cities.$city.spawn.energy, screeps.yoner.cities.$city.spawn.energyTotal)"
      }
     ]
    },
    {
     "title": "Wall height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(movingAverage(screeps.yoner.cities.$city.wall, '5min'), 'Wall height')"
      }
     ]
    }
   ]
  }
 ]
}