{
 "title": "Screeps Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU info",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(screeps.yoner.cpu.getUsed, '10hour'), 'CPU - 10 hr')"
    },
    {
     "target": "alias(screeps.yoner.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(movingAverage(screeps.yoner.cpu.getUsed, '30min'), 'CPU - 30 min')"
    }
   ]
  },
  {
   "title": "10 Min CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "movingAverage(screeps.yoner.cpu.getUsed, '10min')"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "City Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByTotal(aliasByNode(screeps.yoner.cities.*.count, 3))"
    }
   ]
  },
  {
   "title": "City CPU - top 5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "limit(sortByTotal(aliasByNode(screeps.yoner.cities.*.cpu, 3)), 5)"
    }
   ]
  },
  {
   "title": "Creep Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByTotal(aliasByNode(currentAbove(screeps.yoner.creeps.*.count, 0.5), 3))"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowPercentile(removeAbovePercentile(diffSeries(screeps.yoner.market.credits, #A), 99.5), 1), '1d Credits')",
     "targetFull": "alias(removeBelowPercentile(removeAbovePercentile(diffSeries(screeps.yoner.market.credits, movingAverage(timeShift(screeps.yoner.market.credits, '1d'), 5)), 99.5), 1), '1d Credits')"
    },
    {
     "target": "alias(screeps.yoner.market.credits, 'Credits')"
    }
   ]
  },
  {
   "title": "GCL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.yoner.gcl.level" }
   ]
  },
  {
   "title": "GCL 1 Day",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "diffSeries(movingAverage(screeps.yoner.gcl.total, '5min'), #A)",
     "targetFull": "diffSeries(movingAverage(screeps.yoner.gcl.total, '5min'), timeShift(movingAverage(screeps.yoner.gcl.total, '5min'), '1d'))"
    }
   ]
  },
  {
   "title": "GPL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.yoner.gpl.level" }
   ]
  },
  {
   "title": "GPL 1 Day",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "diffSeries(movingAverage(screeps.yoner.gpl.total, '5min'), #A)",
     "targetFull": "diffSeries(movingAverage(screeps.yoner.gpl.total, '5min'), timeShift(movingAverage(screeps.yoner.gpl.total, '5min'), '1d'))"
    }
   ]
  },
  {
   "title": "Energy on the Floor",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "screeps.yoner.energy" }
   ]
  },
  {
   "title": "City count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "countSeries(currentAbove(screeps.yoner.cities.*.rcl.level, 0))"
    }
   ]
  },
  {
   "title": "GCL Production",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 2, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(diffSeries(movingAverage(removeAbovePercentile(screeps.yoner.gcl.total, 99), '10min'), #A), 0), 'GCL per hour')",
     "targetFull": "alias(removeBelowValue(diffSeries(movingAverage(removeAbovePercentile(screeps.yoner.gcl.total, 99), '10min'), timeShift(movingAverage(removeAbovePercentile(screeps.yoner.gcl.total, 99), '10min'), '1h')), 0), 'GCL per hour')"
    }
   ]
  },
  {
   "title": "GPL Production",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(removeBelowValue(diffSeries(movingAverage(removeAbovePercentile(screeps.yoner.gpl.total, 99), '10min'), #A), 0), 'Power per hour')",
     "targetFull": "alias(removeBelowValue(diffSeries(movingAverage(removeAbovePercentile(screeps.yoner.gpl.total, 99), '10min'), movingAverage(timeShift(removeAbovePercentile(screeps.yoner.gpl.total, 99), '1h'), '10min')), 0), 'Power per hour')"
    },
    {
     "refCount": 1,
     "target": "alias(removeBelowValue(diffSeries(movingAverage(removeAbovePercentile(screeps.yoner.gpl.total, 99), '12hour'), #C), 0), '12 hour')",
     "targetFull": "alias(removeBelowValue(diffSeries(movingAverage(removeAbovePercentile(screeps.yoner.gpl.total, 99), '12hour'), movingAverage(timeShift(removeAbovePercentile(screeps.yoner.gpl.total, 99), '1h'), '12hour')), 0), '12 hour')"
    }
   ]
  },
  {
   "title": "Resource Mining",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scale(movingAverage(#A, '1hour'), 60), 'Resources per hour')",
     "targetFull": "alias(scale(movingAverage(sumSeries(screeps.yoner.cities.*.deposits), '1hour'), 60), 'Resources per hour')"
    },
    {
     "target": "alias(scale(movingAverage(#A, '3d'), 60), '3 day moving average')",
     "targetFull": "alias(scale(movingAverage(sumSeries(screeps.yoner.cities.*.deposits), '3d'), 60), '3 day moving average')"
    }
   ]
  },
  {
   "title": "Mineral Mining",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scale(movingAverage(#A, '1hour'), 60), 'Minerals per hour')",
     "targetFull": "alias(scale(movingAverage(sumSeries(screeps.yoner.cities.*.minerals), '1hour'), 60), 'Minerals per hour')"
    },
    {
     "target": "alias(scale(movingAverage(#A, '3d'), 60), '3 day moving average')",
     "targetFull": "alias(scale(movingAverage(sumSeries(screeps.yoner.cities.*.minerals), '3d'), 60), '3 day moving average')"
    }
   ]
  },
  {
   "title": "CPU by role",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByTotal(aliasByNode(movingAverage(removeAbovePercentile(screeps.yoner.profiler.*.run.time, 99), '3day'), 3))"
    }
   ]
  },
  {
   "title": "CPU by role",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByTotal(aliasByNode(movingAverage(removeAbovePercentile(screeps.yoner.profiler.*.run.time, 99), '10min'), 3, 4))"
    }
   ]
  },
  {
   "title": "Profiler: Function cpu usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "limit(sortByTotal(aliasByNode(movingAverage(removeAbovePercentile(transformNull(screeps.yoner.profiler.*.*.time, 0), 99), '10min'), 3, 4)), 10)"
    }
   ]
  },
  {
   "title": "RCL - bottom 5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(limit(currentAbove(scale(sortByTotal(scale(movingAverage(screeps.yoner.cities.*.rcl.level, 10), -1)), -1), 0), 5), 3)"
    }
   ]
  },
  {
   "title": "Walls - bottom 5",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(limit(sortByTotal(scale(screeps.yoner.cities.*.wall, -1)), 5), -1), 3)"
    }
   ]
  },
  {
   "title": "Bucket Change rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.yoner.cpu.bucketfillRateMax)"
    }
   ]
  },
  {
   "title": "Stored Energy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sumSeries(screeps.yoner.cities.*.storage.energy))"
    }
   ]
  },
  {
   "title": "Constrution Progress",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maximumAbove(aliasByNode(screeps.yoner.cities.*.sites.progress, 3, 5), 0)"
    },
    {
     "target": "maximumAbove(aliasByNode(screeps.yoner.cities.*.sites.progressTotal, 3, 5), 0)"
    }
   ]
  },
  {
   "title": "CPU Waste",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.yoner.cpu.waste)"
    }
   ]
  },
  {
   "title": "Room Attacks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maximumAbove(aliasByNode(maximumAbove(screeps.yoner.rooms.*.attacks, 0), 3), 0)"
    }
   ]
  },
  {
   "title": "Creep Attacks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(screeps.yoner.creeps.*.attacks, 0), 3)"
    }
   ]
  },
  {
   "title": "Enemy Sightings",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.yoner.enemies.*)"
    }
   ]
  },
  {
   "title": "Observer Scans",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sumSeries(screeps.yoner.cities.*.scans))"
    }
   ]
  },
  {
   "title": "Scans per hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 80 },
   "targets": [
    {
     "target": "aliasByMetric(scale(movingAverage(sumSeries(perSecond(screeps.yoner.cities.*.scans)), '24hour'), 3600))"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 80 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(screeps.yoner.heap.available, 2, 3)"
    }
   ]
  },
  {
   "title": "Leaderboard ranks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(screeps.yoner.leaderboard.rank, 2, 3)"
    },
    {
     "target": "aliasByNode(screeps.yoner.leaderboard_power.rank, 2, 3)"
    }
   ]
  }
 ]
}