{
 "title": "Resource Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tier 0 resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.wire)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.cell)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.alloy)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.condensate)"
    },
    {
     "target": "alias(sumSeries(#A, #B, #D, #C), 'Sum')",
     "targetFull": "alias(sumSeries(aliasByMetric(screeps.yoner.resource.wire), aliasByMetric(screeps.yoner.resource.cell), aliasByMetric(screeps.yoner.resource.condensate), aliasByMetric(screeps.yoner.resource.alloy)), 'Sum')"
    }
   ]
  },
  {
   "title": "Tier 1 resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.switch)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.phlegm)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.tube)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.concentrate)"
    },
    {
     "target": "alias(sumSeries(#A, #B, #D, #C), 'Sum')",
     "targetFull": "alias(sumSeries(aliasByMetric(screeps.yoner.resource.switch), aliasByMetric(screeps.yoner.resource.phlegm), aliasByMetric(screeps.yoner.resource.concentrate), aliasByMetric(screeps.yoner.resource.tube)), 'Sum')"
    }
   ]
  },
  {
   "title": "Tier 2 resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.transistor)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.tissue)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.fixtures)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.extract)"
    },
    {
     "target": "alias(sumSeries(#A, #B, #D, #C), 'Sum')",
     "targetFull": "alias(sumSeries(aliasByMetric(screeps.yoner.resource.transistor), aliasByMetric(screeps.yoner.resource.tissue), aliasByMetric(screeps.yoner.resource.extract), aliasByMetric(screeps.yoner.resource.fixtures)), 'Sum')"
    }
   ]
  },
  {
   "title": "Tier 3 resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.microchip)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.muscle)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.frame)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.spirit)"
    },
    {
     "target": "alias(sumSeries(#A, #B, #D, #C), 'Sum')",
     "targetFull": "alias(sumSeries(aliasByMetric(screeps.yoner.resource.microchip), aliasByMetric(screeps.yoner.resource.muscle), aliasByMetric(screeps.yoner.resource.spirit), aliasByMetric(screeps.yoner.resource.frame)), 'Sum')"
    }
   ]
  },
  {
   "title": "Tier 4 resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.circuit)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.organoid)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.hydraulics)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.emanation)"
    },
    {
     "target": "alias(sumSeries(#A, #B, #D, #C), 'Sum')",
     "targetFull": "alias(sumSeries(aliasByMetric(screeps.yoner.resource.circuit), aliasByMetric(screeps.yoner.resource.organoid), aliasByMetric(screeps.yoner.resource.emanation), aliasByMetric(screeps.yoner.resource.hydraulics)), 'Sum')"
    }
   ]
  },
  {
   "title": "Tier 5 resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.device)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.organism)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.machine)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.essence)"
    },
    {
     "target": "alias(sumSeries(#A, #B, #D, #C), 'Sum')",
     "targetFull": "alias(sumSeries(aliasByMetric(screeps.yoner.resource.device), aliasByMetric(screeps.yoner.resource.organism), aliasByMetric(screeps.yoner.resource.essence), aliasByMetric(screeps.yoner.resource.machine)), 'Sum')"
    }
   ]
  },
  {
   "title": "Base resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.silicon)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.biomass)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.metal)"
    },
    {
     "refCount": 1,
     "target": "aliasByMetric(screeps.yoner.resource.mist)"
    },
    {
     "target": "alias(sumSeries(#A, #B, #D, #C), 'Sum')",
     "targetFull": "alias(sumSeries(aliasByMetric(screeps.yoner.resource.silicon), aliasByMetric(screeps.yoner.resource.biomass), aliasByMetric(screeps.yoner.resource.mist), aliasByMetric(screeps.yoner.resource.metal)), 'Sum')"
    }
   ]
  },
  {
   "title": "Key Resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.yoner.resource.power)"
    },
    {
     "target": "aliasByMetric(screeps.yoner.resource.ops)"
    }
   ]
  },
  {
   "title": "Boosts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.yoner.resource.G)"
    },
    {
     "target": "alias(screeps.yoner.resource.XGH2O, 'upgrade')"
    },
    {
     "target": "alias(screeps.yoner.resource.XLH2O, 'build/repair')"
    },
    {
     "target": "alias(screeps.yoner.resource.XKHO2, 'ranged attack')"
    },
    {
     "target": "alias(screeps.yoner.resource.XLHO2, 'heal')"
    },
    {
     "target": "alias(screeps.yoner.resource.XZHO2, 'move')"
    },
    {
     "target": "alias(screeps.yoner.resource.XGHO2, 'tough')"
    },
    {
     "target": "alias(screeps.yoner.resource.XZH2O, 'dismantle')"
    },
    {
     "target": "alias(screeps.yoner.resource.XUH2O, 'attack')"
    },
    {
     "target": "alias(screeps.yoner.resource.XUHO2, 'harvest')"
    },
    {
     "target": "alias(screeps.yoner.resource.XKH2O, 'carry')"
    }
   ]
  }
 ]
}