import profiler = require("./screeps-profiler")

import lib0 = require("../lib/actions")
import lib1 = require("../roles/breaker")
import lib2 = require("../roles/builder")
import lib3 = require("../managers/city")
import lib4 = require("../roles/claimer")
import lib5 = require("../managers/commodityManager")
import lib6 = require("../roles/defender")
import lib7 = require("../roles/depositMiner")
import lib8 = require("../operations/error")
import lib9 = require("../buildings/factory")
import liba = require("../roles/ferry")
import libb = require("../roles/harasser")
import libc = require("../buildings/labs")
import libd = require("../buildings/link")
import libe = require("../managers/markets")
import libf = require("../roles/medic")
import libg = require("../roles/mineralMiner")
import libh = require("../buildings/observer")
import libi = require("../roles/powerCreep")
import libj = require("../roles/powerMiner")
import libk = require("../roles/quad")
import libl = require("../roles/remoteMiner")
import libm = require("../roles/robber")
import libn = require("../roles/roles")
import libo = require("../managers/roomplan")
import libp = require("../roles/runner")
import libq = require("../config/settings")
import libr = require("../roles/spawnBuilder")
import libs = require("../lib/spawnQueue")
import libt = require("../operations/stats")
import libu = require("../config/template")
import libv = require("../buildings/tower")
import libw = require("../roles/transporter")
import libx = require("../config/types")
import liby = require("../roles/unclaimer")
import libz = require("../roles/upgrader")
import libA = require("../lib/utils")
import libB = require("../roles/repairer")

profiler.registerObject(lib0, "actions")
profiler.registerObject(lib1, "breaker")
profiler.registerObject(lib2, "builder")
profiler.registerObject(lib3, "city")
profiler.registerObject(lib4, "claimer")
profiler.registerObject(lib5, "commodityManager")
profiler.registerObject(lib6, "defender")
profiler.registerObject(lib7, "depositMiner")
profiler.registerObject(lib8, "error")
profiler.registerObject(lib9, "factory")
profiler.registerObject(liba, "ferry")
profiler.registerObject(libb, "harasser")
profiler.registerObject(libc, "labs")
profiler.registerObject(libd, "link")
profiler.registerObject(libe, "markets")
profiler.registerObject(libf, "medic")
profiler.registerObject(libg, "mineralMiner")
profiler.registerObject(libh, "observer")
profiler.registerObject(libi, "powerCreep")
profiler.registerObject(libj, "powerMiner")
profiler.registerObject(libk, "quad")
profiler.registerObject(libl, "remoteMiner")
profiler.registerObject(libm, "robber")
profiler.registerObject(libn, "roles")
profiler.registerObject(libo, "roomplan")
profiler.registerObject(libp, "runner")
profiler.registerObject(libq, "settings")
profiler.registerObject(libr, "spawnBuilder")
profiler.registerObject(libs, "spawnQueue")
profiler.registerObject(libt, "stats")
profiler.registerObject(libu, "template")
profiler.registerObject(libv, "tower")
profiler.registerObject(libw, "transporter")
profiler.registerObject(libx, "types")
profiler.registerObject(liby, "unclaimer")
profiler.registerObject(libz, "upgrader")
profiler.registerObject(libA, "utils")
profiler.registerObject(libB, "repairer")

export = {}