var profiler = require("./screeps-profiler")

const lib0 = require("../lib/actions")
const lib1 = require("../roles/breaker")
const lib2 = require("../roles/builder")
const lib3 = require("../managers/city")
const lib4 = require("../roles/claimer")
const lib5 = require("../managers/commodityManager")
const lib6 = require("../roles/defender")
const lib7 = require("../roles/depositMiner")
const lib8 = require("../operations/error")
const lib9 = require("../buildings/factory")
const liba = require("../roles/ferry")
const libb = require("../roles/harasser")
const libc = require("../buildings/labs")
const libd = require("../buildings/link")
const libe = require("../managers/markets")
const libf = require("../roles/medic")
const libg = require("../roles/mineralMiner")
const libh = require("../buildings/observer")
const libi = require("../roles/powerCreep")
const libj = require("../roles/powerMiner")
const libk = require("../roles/quad")
const libl = require("../roles/remoteMiner")
const libm = require("../roles/robber")
const libn = require("../roles/roles")
const libo = require("../managers/roomplan")
const libp = require("../roles/runner")
const libq = require("../config/settings")
const libr = require("../roles/spawnBuilder")
const libs = require("../lib/spawnQueue")
const libt = require("../operations/stats")
const libu = require("../config/template")
const libv = require("../buildings/tower")
const libw = require("../roles/transporter")
const libx = require("../config/types")
const liby = require("../roles/unclaimer")
const libz = require("../roles/upgrader")
const libA = require("../lib/utils")

profiler.registerObject(lib0, "../lib/actions")
profiler.registerObject(lib1, "../roles/breaker")
profiler.registerObject(lib2, "../roles/builder")
profiler.registerObject(lib3, "../managers/city")
profiler.registerObject(lib4, "../roles/claimer")
profiler.registerObject(lib5, "../managers/commodityManager")
profiler.registerObject(lib6, "../roles/defender")
profiler.registerObject(lib7, "../roles/depositMiner")
profiler.registerObject(lib8, "../operations/error")
profiler.registerObject(lib9, "../buildings/factory")
profiler.registerObject(liba, "../roles/ferry")
profiler.registerObject(libb, "../roles/harasser")
profiler.registerObject(libc, "../buildings/labs")
profiler.registerObject(libd, "../buildings/link")
profiler.registerObject(libe, "../managers/markets")
profiler.registerObject(libf, "../roles/medic")
profiler.registerObject(libg, "../roles/mineralMiner")
profiler.registerObject(libh, "../buildings/observer")
profiler.registerObject(libi, "../roles/powerCreep")
profiler.registerObject(libj, "../roles/powerMiner")
profiler.registerObject(libk, "../roles/quad")
profiler.registerObject(libl, "../roles/remoteMiner")
profiler.registerObject(libm, "../roles/robber")
profiler.registerObject(libn, "../roles/roles")
profiler.registerObject(libo, "../managers/roomplan")
profiler.registerObject(libp, "../roles/runner")
profiler.registerObject(libq, "../config/settings")
profiler.registerObject(libr, "../roles/spawnBuilder")
profiler.registerObject(libs, "../lib/spawnQueue")
profiler.registerObject(libt, "../operations/stats")
profiler.registerObject(libu, "../config/template")
profiler.registerObject(libv, "../buildings/tower")
profiler.registerObject(libw, "../roles/transporter")
profiler.registerObject(libx, "../config/types")
profiler.registerObject(liby, "../roles/unclaimer")
profiler.registerObject(libz, "../roles/upgrader")
profiler.registerObject(libA, "../lib/utils")

module.exports = {}