var profiler = require("./screeps-profiler")

const lib0 = require("./actions")
const lib1 = require("./breaker")
const lib2 = require("./builder")
const lib3 = require("./city")
const lib4 = require("./claimer")
const lib5 = require("./commodityManager")
const lib6 = require("./defender")
const lib7 = require("./depositMiner")
const lib8 = require("./error")
const lib9 = require("./factory")
const liba = require("./ferry")
const libb = require("./harasser")
const libc = require("./labs")
const libd = require("./link")
const libe = require("./markets")
const libf = require("./medic")
const libg = require("./mineralMiner")
const libh = require("./observer")
const libi = require("./powerCreep")
const libj = require("./powerMiner")
const libk = require("./quad")
const libl = require("./remoteMiner")
const libm = require("./robber")
const libn = require("./roles")
const libo = require("./roomplan")
const libp = require("./runner")
const libq = require("./settings")
const libr = require("./spawnBuilder")
const libs = require("./spawnQueue")
const libt = require("./stats")
const libu = require("./template")
const libv = require("./tower")
const libw = require("./transporter")
const libx = require("./types")
const liby = require("./unclaimer")
const libz = require("./upgrader")
const libA = require("./utils")

profiler.registerObject(lib0, "./actions")
profiler.registerObject(lib1, "./breaker")
profiler.registerObject(lib2, "./builder")
profiler.registerObject(lib3, "./city")
profiler.registerObject(lib4, "./claimer")
profiler.registerObject(lib5, "./commodityManager")
profiler.registerObject(lib6, "./defender")
profiler.registerObject(lib7, "./depositMiner")
profiler.registerObject(lib8, "./error")
profiler.registerObject(lib9, "./factory")
profiler.registerObject(liba, "./ferry")
profiler.registerObject(libb, "./harasser")
profiler.registerObject(libc, "./labs")
profiler.registerObject(libd, "./link")
profiler.registerObject(libe, "./markets")
profiler.registerObject(libf, "./medic")
profiler.registerObject(libg, "./mineralMiner")
profiler.registerObject(libh, "./observer")
profiler.registerObject(libi, "./powerCreep")
profiler.registerObject(libj, "./powerMiner")
profiler.registerObject(libk, "./quad")
profiler.registerObject(libl, "./remoteMiner")
profiler.registerObject(libm, "./robber")
profiler.registerObject(libn, "./roles")
profiler.registerObject(libo, "./roomplan")
profiler.registerObject(libp, "./runner")
profiler.registerObject(libq, "./settings")
profiler.registerObject(libr, "./spawnBuilder")
profiler.registerObject(libs, "./spawnQueue")
profiler.registerObject(libt, "./stats")
profiler.registerObject(libu, "./template")
profiler.registerObject(libv, "./tower")
profiler.registerObject(libw, "./transporter")
profiler.registerObject(libx, "./types")
profiler.registerObject(liby, "./unclaimer")
profiler.registerObject(libz, "./upgrader")
profiler.registerObject(libA, "./utils")

module.exports = {}